ccflags-y += -DMHL_VERSION_MAJOR="0x30"
ccflags-y += -DMHL_VERSION_MINOR="00"
ifeq ($(FEATURE_SUPPORT_UNPOWERED_DONGLE), true)
ccflags-y += -DMHL_SUPPORT_UNPOWERED_DONGLE
endif

ifeq ($(MHL_SUPPORT_CHG_TIMING), true)
ccflags-y += -DSUPPORT_CHG_TIMING
endif

EXTRA_CFLAGS += -fno-pic

ccflags-y += -DMHL2_DRIVE_STRENGTH_DP_CTL1="0xFE"
ccflags-y += -DMHL2_DRIVE_STRENGTH_DP_CTL6="0x2A"
ccflags-y += -DMHL2_DRIVE_STRENGTH_DP_CTL7="0x08"
ccflags-y += -DMHL2_DRIVE_STRENGTH_DP_CTL8="0x00"
ccflags-y += -DMHL2_DRIVE_STRENGTH_COC_CTL1="0x07"
ccflags-y += -DMHL3_DRIVE_STRENGTH_DP_CTL1="0xA2"
ccflags-y += -DMHL3_DRIVE_STRENGTH_DP_CTL6="0x02"
ccflags-y += -DMHL3_DRIVE_STRENGTH_DP_CTL7="0x08"
ccflags-y += -DMHL3_DRIVE_STRENGTH_DP_CTL8="0x00"
ccflags-y += -DMHL3_DRIVE_STRENGTH_COC_CTL1="0xBC"

ccflags-y += -Idrivers/video/msm/mdss

obj-y += mhl_platform_base.o
obj-y += mhl_platform_power.o
obj-y += mhl_platform.o
obj-y += mhl_platform_i2c.o

obj-y += mhl_sii8620_8061_drv.o

#BIST Support
ifeq ($(CFG_MHL_BIST),true)
ccflags-y += -DMHL_BIST
mhl_sii8620_8061_drv-objs := mhl_sii8620_bist.o
endif

ccflags-y += -DMHL_UPSTREAM_HPD_PUSH_PULL
ccflags-y += -DMHL_HPD_UPSTREAM_HDMI_IS_HIGH_TRIGGER

ccflags-y += -DMHL_DEVICE_ID="0x05"

mhl_sii8620_8061_drv-objs += mhl_driver.o mhl_tx.o mhl_sii8620_8061_device.o mhl_sii8620_device_edid.o mhl_lib_edid.o mhl_cbus_control.o mhl_tx_rcp.o mhl_lib_infoframe.o mhl_lib_timer.o mhl_cbus_write_burst.o mhl_support_unpowered_dongle.o
